name: docfx-build-publishs

on:
  push:
    branches: [ mohanpaladugu-patch-1 ]
  pull_request:
    branches: [ mohanpaladugu-patch-1 ]
jobs:
  generate-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '5.0.x'
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
          
      - name: Install dependencies
        run: dotnet restore  ./VirtualEconomyFramework/VEDriversLite
        
      - name: DocFX Build
        working-directory: ./VirtualEconomyFramework/VEDriversLite/
        run: docfx docfx.json
        
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./VirtualEconomyFramework/VEDriversLite/_site
