name: Build with sonarqubes
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting for sonarcloud
        fetch-depth: 0
    - name: Setup .Net SDK (v5.0)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Build
      run: dotnet build ./VirtualEconomyFramework/VEFrameworkUnitTest/VEFrameworkUnitTest.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./VirtualEconomyFramework/VEFrameworkUnitTest/VEFrameworkUnitTest.csproj --blame --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=opencover.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
       projectBaseDir: my-custom-directory
        -Dsonar.organization=mohanpaladugu
        -Dsonar.projectKey=mohanpaladugu_VirtualEconomyFramework
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
